{% set name = "azure-purview-administration" %}
{% set version = "1.0.0b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-purview-administration-{{ version }}.zip
  sha256: d04271dc3b73904d3b5fbc1ab43c6658ebec53ac84f1c3d4386b76a7e82808d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - azure-core <2.0.0,>=1.18.0
    - msrest >=0.6.21
    - six >=1.11.0
    - typing

test:
  imports:
    - azure.purview.administration
    - azure.purview.administration.account
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Purview Administration Client Library for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - redur
